### PR TITLE
Add separate readme for bottom panel example

### PR DESCRIPTION
**Pull request by sundaram123krishnan**

### CODE REVIEW

**Comment by sundaram123krishnan** [comment]
I think i ran into some problem, added separate readme for the example

**Comment by sundaram123krishnan** [comment]
Maybe u can grant me collaborator access? so that i can work on branches which makes our life much easier?

**Comment by sundaram123krishnan** [comment]
Willing to contribute more to this repo

**Comment by Decodetalkers** [comment]
Ok. I will send you an invitation

**Comment by Decodetalkers** [comment]
Thank you

**Comment by sundaram123krishnan** [comment]
Received, thx

**Comment by Decodetalkers** [comment]
And can you join our discord?

**Comment by sundaram123krishnan** [comment]
> Emm.. One suggestion. next time you make pr, maybe you should checkout a new branch, so that I can help fix some problems for you 

Sure

**Comment by Decodetalkers** [comment]
> > And can you join our discord?
> 
> Yes, willing to Can u share the link ?

https://discord.gg/KKZRDYrRYW

**Comment by sundaram123krishnan** [comment]
Joined, thx

**Pull request merged**
