### PR TITLE
added support of enum visibility to the `to_layer_message` attribute

### PR DESCRIPTION
**Pull request by tukanoidd**
Hi, updated the library in a personal project of mine, and due to how I structured my project, supporting my AppMsg visibility is important, so I added the feature in :)

### CODE REVIEW

**Comment by Decodetalkers** [comment]
I see, this is the mark of pub pub(crate), right?

**Review by Decodetalkers — APPROVED** [review]

**Comment by tukanoidd** [comment]
> I see, this is the mark of pub pub(crate), right?

yep

**Comment by Decodetalkers** [comment]
And do you know a better way to pass derive to the derive made enum? now I set the derive as input.. but I do not think it is the best way...

**Comment by Decodetalkers** [comment]
Thank you very much!!

**Comment by tukanoidd** [comment]
> And do you know a better way to pass derive to the derive made enum? now I set the derive as input.. but I do not think it is the best way...

Ye, I prefer to use this crate for typed parsing of macros https://docs.rs/darling/latest/darling/ and it works well with syn, quote and proc-macro2

**Comment by tukanoidd** [comment]
I could help with a refactor when i have free time :)

**Comment by Decodetalkers** [comment]
Thank you!

**Pull request merged**
