### PR TITLE
chore: viewport support demo

### PR DESCRIPTION
**Pull request by Decodetalkers**

### CODE REVIEW

**Comment by MalpenZibo** [comment]
Nice! I think that the mouse position should be fixed. I tried with the following code:
```
    pub fn cursor(&self) -> IcedMouse::Cursor {
        self.mouse_position
            .map(|point| Point {
                x: (point.x * self.wayland_scale_factor as f32) / self.scale_factor() as f32,
                y: (point.y * self.wayland_scale_factor as f32) / self.scale_factor() as f32,
            })
            .map(IcedMouse::Cursor::Available)
            .unwrap_or(IcedMouse::Cursor::Unavailable)
    }
```

**Comment by Decodetalkers** [comment]
> Nice! I think that the mouse position should be fixed. I tried with the following code:
> 
> ```
>     pub fn cursor(&self) -> IcedMouse::Cursor {
>         self.mouse_position
>             .map(|point| Point {
>                 x: (point.x * self.wayland_scale_factor as f32) / self.scale_factor() as f32,
>                 y: (point.y * self.wayland_scale_factor as f32) / self.scale_factor() as f32,
>             })
>             .map(IcedMouse::Cursor::Available)
>             .unwrap_or(IcedMouse::Cursor::Unavailable)
>     }
> ```

Ok. I think it is ok. can you take a try?

**Comment by MalpenZibo** [comment]
> > Nice! I think that the mouse position should be fixed. I tried with the following code:
> > ```
> >     pub fn cursor(&self) -> IcedMouse::Cursor {
> >         self.mouse_position
> >             .map(|point| Point {
> >                 x: (point.x * self.wayland_scale_factor as f32) / self.scale_factor() as f32,
> >                 y: (point.y * self.wayland_scale_factor as f32) / self.scale_factor() as f32,
> >             })
> >             .map(IcedMouse::Cursor::Available)
> >             .unwrap_or(IcedMouse::Cursor::Unavailable)
> >     }
> > ```
> 
> Ok. I think it is ok. can you take a try?

It works! I tried to use the `counter_multi` example on two different monitors (with StartMode::AllScreens) one with HiDPI and a "normal" one.

No blurry interface and the mouse worked well on both layers!

**Comment by Decodetalkers** [comment]
Ok, I will merge it

**Pull request merged**
